// Auto-generated by train_model.py
#pragma once

struct ShakeModel {
    static constexpr float W0 = 2.36757366f;
    static constexpr float W1 = -0.61378810f;
    static constexpr float W2 = -0.17619904f;
    static constexpr float W3 = 0.32548094f;
};

// Feature extraction params
#define WINDOW_SIZE 50
#define STEP_SIZE   25
